name: Test Workflow

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f3001829@ds.study.iitm.ac.in
        run: echo "Hello, world! Workflow triggered successfully."
